workflows:
  android:
    name: Hello world workflow android
    scripts:
      - echo "Hello World!"
      - name : android test
        script: ./gradlew test
        test_report: app/build/test-results/**/*.xml

      - name: android build
        script: ./gradlew build

    artifacts:
      - app/build/outputs/**/**/*.apk